{
 "title": "Wifi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Packet Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(cpe_wifi_receive_broadcast_frames[$__rate_interval]) + rate(cpe_wifi_receive_unicast_frames[$__rate_interval])",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - in"
    },
    {
     "expr": "rate(cpe_wifi_transmit_frames[$__rate_interval])",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - out"
    }
   ]
  },
  {
   "title": "Wireless Noise",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cpe_wifi_noise{}",
     "legendFormat": "{{wlan_interface}}: {{client_mac}}"
    }
   ]
  },
  {
   "title": "Wifi Quality (Out of 5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "cpe_wifi_quality",
     "legendFormat": "{{wlan_interface}}: {{client_mac}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cpe_wifi_rssi{}",
     "legendFormat": "{{wlan_interface}}: {{client_mac}}"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cpe_wifi_snr{}",
     "legendFormat": "{{wlan_interface}}: {{client_mac}}"
    }
   ]
  },
  {
   "title": "Max Packet Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "cpe_wifi_transmit_rate",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - out"
    },
    {
     "expr": "cpe_wifi_receive_rate",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - in"
    }
   ]
  },
  {
   "title": "Broken Things",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(cpe_wifi_transmit_errors[$__rate_interval])",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - Errors"
    },
    {
     "expr": "rate(cpe_wifi_transmit_retries[$__rate_interval])",
     "legendFormat": "{{wlan_interface}}: {{client_mac}} - Retries"
    }
   ]
  }
 ]
}