{
 "title": "Zhone",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(cpe_receive_bytes{interface!~\"wl.*\"}[$__rate_interval])*8",
     "legendFormat": "{{interface}} - {{interface_name}} - in"
    },
    {
     "expr": "rate(cpe_transmit_bytes{interface!~\"wl.*\"}[$__rate_interval])*8",
     "legendFormat": "{{interface}} - {{interface_name}} - out"
    }
   ]
  },
  {
   "title": "GPON Transceiver Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cpe_gpon_receive_power{}",
     "legendFormat": "{{interface}} - {{interface_name}} RX"
    },
    {
     "expr": "cpe_gpon_transmit_power{}",
     "legendFormat": "{{interface}} - {{interface_name}} TX"
    }
   ]
  },
  {
   "title": "Interface Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(cpe_receive_drops{interface!~\"wl.*\"}[$__rate_interval])",
     "legendFormat": "{{interface}} - {{interface_name}} - in"
    },
    {
     "expr": "rate(cpe_transmit_drops{interface!~\"wl.*\"}[$__rate_interval])",
     "legendFormat": "{{interface}} - {{interface_name}} - out"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "cpe_if_status{}",
     "legendFormat": "{{interface}} - {{interface_name}}"
    }
   ]
  }
 ]
}